name: Building # Nombre del workflow
on: # Ejecución condicional
  push:
#    tags:
#      - "v*.*.*" # Filtra los pushes de forma que solo los que tenga una etiqueta con esta expresión 

    jobs: # Solo haremos uno
      building:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3 # Copiamos el repositorio
          - uses: actions/setup-python@v4
            with:
              python-version: '3.10'
          - name: Install Poetry
            uses: snok/install-poetry@v1
          - run: poetry build --junitxml=jest-junit.xml
          - name: Publish to GH Releases
            uses: dorny/test-reporter@v1
            if: success() || failure()
            with:
              name: Test
              path: reports/jest-*.xml
              reporter: jest-junit